#!/usr/local/bin/booking-perl

# for use on office-staging.prod.booking.com

use warnings;
use strict;
use feature 'say';

my ($app_name, $template) = @ARGV;
die "Please specify app name as the first command-line parameter (and alternatevly role template name as second)" unless $app_name;
$template //= 'partner_funnel';

use Bookings::XY::Token;

for my $user ($app_name) {
    printf "Created %s key/secret pair: %s %s\n", $user, Bookings::XY::Token::generate_key_and_token(
        'ticket_data' => {
          'identity' => {
            'app_name' => $user,
            'graphite_category' => 'developer'
          },
          'rights' => {
            'error_detail' => 1
          }
        },
        'ticket_template' => $template
    );
}

say "DONE";